spring.application.name=booking

server.port=${PORT:8050}
spring.jpa.show-sql=true


spring.web.error.include-message=always

# ==============================
# PostgreSQL Database
# ==============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update


# ==============================
# Frontend URL / CORS
# ==============================

app.frontend-url=${FRONTEND_URL}


# ==============================
# Brevo Email API
# ==============================

brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=${BREVO_SENDER_EMAIL}
brevo.sender-name=${BREVO_SENDER_NAME:Royal Spice}
brevo.receiver-email=${CONTACT_RECEIVER}


# JWT
app.jwt.secret=${JWT_SECRET}
